language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: 11c10c16a15c313a01e098e6f8554c8f2bb2516c
 local_dir: dist
 on:
   branch: travisCI

